[package]
name = "elem"
version = "0.1.0"
edition = "2021"

[dependencies]
cxx = "1.0.131"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"

[build-dependencies]
cxx-build = "1.0.131"

[[example]]
name = "static"
crate-type = ["staticlib"]
