[package]
name = "elem"
version = "0.1.0"
edition = "2021"

[dependencies]
cxx = "1.0.131"
hound = "3.5.1"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
tokio = { version = "1.41.1", features = ["full"] }

[build-dependencies]
cxx-build = "1.0.131"
